@extends('layouts.app')
@php($pageTitle = 'Messages · '.$tontine->name)
@section('content')
<div class="page-heading"><div><a href="{{ route('tontines.show',$tontine) }}" class="small fw-bold"><i class="bi bi-arrow-left me-1"></i>{{ $tontine->name }}</a><h1 class="mt-2">Vie de la communauté</h1><p>Partagez les décisions, les rappels et les informations importantes.</p></div><span class="badge-soft success"><i class="bi bi-chat-dots me-1"></i>Espace privé</span></div>
<div class="row g-4">
    <div class="col-xl-8"><div class="panel-card"><div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="panel-title">Fil de discussion</h3><span class="panel-subtitle">Les messages restent liés à cette tontine.</span></div><span class="text-muted small">{{ $messages->total() }} message{{ $messages->total() > 1 ? 's' : '' }}</span></div>
        @forelse($messages as $message)<article class="message-card {{ $message->type === 'important' ? 'important' : ($message->type === 'announcement' ? 'announcement' : '') }}"><div class="d-flex align-items-start gap-3"><span class="avatar">{{ strtoupper(substr($message->user->name,0,1)) }}</span><div class="flex-grow-1"><div class="d-flex align-items-center gap-2 flex-wrap"><strong>{{ $message->user->name }}</strong>@if($message->type !== 'normal')<span class="badge-soft {{ $message->type === 'important' ? 'danger' : 'warning' }}">{{ $message->type === 'important' ? 'Important' : 'Annonce' }}</span>@endif<span class="text-muted small">· {{ $message->created_at->diffForHumans() }}</span></div><p class="message-body">{{ $message->body }}</p>@if($message->edited_at)<small class="text-muted">Modifié</small>@endif</div>@can('delete',$message)<form method="POST" action="{{ route('messages.destroy',$message) }}" data-confirm="Supprimer ce message ?">@csrf @method('DELETE')<button class="btn btn-sm btn-light text-danger" title="Supprimer"><i class="bi bi-trash"></i></button></form>@endcan</div></article>@empty<div class="empty-state"><i class="bi bi-chat-square-text"></i><h5>La conversation commence ici</h5><p>Publiez le premier message pour informer votre communauté.</p></div>@endforelse
        {{ $messages->links() }}
    </div></div>
    <div class="col-xl-4"><div class="panel-card sticky-xl-top" style="top: 105px"><div class="mb-4"><span class="eyebrow blue">NOUVEAU MESSAGE</span><h3 class="panel-title mt-2">Informer le groupe</h3><span class="panel-subtitle">Un message clair évite les malentendus.</span></div><form method="POST" action="{{ route('messages.store',$tontine) }}">@csrf<div class="mb-3"><label class="form-label">Type de message</label><select name="type" class="form-select"><option value="normal">Message général</option><option value="announcement">Annonce de la gestion</option><option value="important">Important / urgent</option></select></div><div class="mb-3"><label class="form-label">Votre message</label><textarea name="body" rows="7" class="form-control" placeholder="Ex : La prochaine cotisation est attendue avant le 10 du mois..." required></textarea></div><button class="btn btn-primary w-100"><i class="bi bi-send me-2"></i>Publier le message</button></form><div class="soft-callout mt-4"><i class="bi bi-lightbulb"></i><span>Les messages importants sont mis en évidence pour toute la communauté.</span></div></div></div>
</div>
@endsection