@extends('layouts.app')
@php($pageTitle = 'Réglages · '.$tontine->name)
@section('content')
<div class="page-heading"><div><a href="{{ route('tontines.show',$tontine) }}" class="small fw-bold"><i class="bi bi-arrow-left me-1"></i>Retour à la tontine</a><h1 class="mt-2">Réglages de la tontine</h1><p>Faites évoluer le cadre de votre communauté sans perdre son historique.</p></div><span class="badge-soft">{{ ucfirst($tontine->status) }}</span></div>
<div class="row justify-content-center"><div class="col-xl-9"><div class="panel-card"><form method="POST" action="{{ route('tontines.update',$tontine) }}" class="row g-4">@csrf @method('PUT')
    <div class="col-12"><label class="form-label">Nom de la tontine</label><input name="name" class="form-control form-control-lg" value="{{ old('name',$tontine->name) }}" required><div class="form-text">Un nom court et reconnaissable aide vos membres à retrouver la bonne communauté.</div></div>
    <div class="col-12"><label class="form-label">Description</label><textarea name="description" rows="3" class="form-control">{{ old('description',$tontine->description) }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Type</label><select name="type" class="form-select">@foreach(['association'=>'Association','dahira'=>'Dahira','famille'=>'Famille','amis'=>'Groupe d’amis','professionnel'=>'Professionnel','asc'=>'ASC','autre'=>'Autre'] as $value=>$label)<option value="{{ $value }}" @selected(old('type',$tontine->type)===$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Visibilité</label><select name="visibility" class="form-select"><option value="private" @selected(old('visibility',$tontine->visibility)==='private')>Privée — sur invitation</option><option value="public" @selected(old('visibility',$tontine->visibility)==='public')>Publique — visible par tous</option></select></div>
    <div class="col-md-4"><label class="form-label">Fréquence</label><select name="frequency" class="form-select">@foreach(['weekly'=>'Hebdomadaire','monthly'=>'Mensuelle','quarterly'=>'Trimestrielle','yearly'=>'Annuelle'] as $value=>$label)<option value="{{ $value }}" @selected(old('frequency',$tontine->frequency)===$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Montant de cotisation</label><div class="input-group"><input type="number" min="0" name="contribution_amount" class="form-control" value="{{ old('contribution_amount',$tontine->contribution_amount) }}" required><span class="input-group-text">FCFA</span></div></div>
    <div class="col-md-4"><label class="form-label">Date de début</label><input type="date" name="starts_at" class="form-control" value="{{ old('starts_at',$tontine->starts_at?->format('Y-m-d')) }}" required></div>
    <div class="col-md-6"><label class="form-label">État de la tontine</label><select name="status" class="form-select"><option value="active" @selected(old('status',$tontine->status)==='active')>Active — les opérations continuent</option><option value="paused" @selected(old('status',$tontine->status)==='paused')>En pause — suspendre temporairement</option><option value="archived" @selected(old('status',$tontine->status)==='archived')>Archivée — conserver l’historique</option></select></div>
    <div class="col-12"><label class="form-label">Règles de la communauté</label><textarea name="rules" rows="5" class="form-control" placeholder="Échéances, validation, rotation des bénéficiaires...">{{ old('rules',$tontine->rules) }}</textarea></div>
    <div class="col-12 d-flex justify-content-end gap-2 pt-2"><a href="{{ route('tontines.show',$tontine) }}" class="btn btn-light">Annuler</a><button class="btn btn-primary"><i class="bi bi-check2 me-2"></i>Enregistrer les réglages</button></div>
</form></div></div></div>
@endsection